### ISSUE TITLE
Compilation error with Swift 3.2 and Xcode 9

### ISSUE THREAD

**Issue by paulyhedral** [chrisamanse/CryptoKit#1]
When trying to build the latest version of this library (0.3.7) as a CocoaPod, using Swift 3.2 in Xcode 9 beta 1, the following compilation errors occur:

`.../CryptoKit/Sources/CryptoKit/Hash Algorithms/Implementations/SHA-2/SHA2Variant.swift:66:34: Binary operator '&+' cannot be applied to two 'Self.BaseUnit' operands`
`.../CryptoKit/Sources/CryptoKit/Hash Algorithms/Implementations/SHA-2/SHA2Variant.swift:75:31: Binary operator '&+' cannot be applied to two 'Self.BaseUnit' operands`
`.../CryptoKit/Sources/CryptoKit/Hash Algorithms/Implementations/SHA-2/SHA2Variant.swift:78:32: Binary operator '&+' cannot be applied to two 'Self.BaseUnit' operands`
`.../CryptoKit/Sources/CryptoKit/Hash Algorithms/Implementations/SHA-2/SHA2Variant.swift:95:29: Binary operator '&+' cannot be applied to two 'Self.BaseUnit' operands`

**Comment by chrisamanse** [comment]
Thanks for testing and reporting. Updated code and placed in [swift-3.2](https://github.com/chrisamanse/CryptoKit/tree/swift-3.2) branch. Reopen if still failing.
